"""migrate

Revision ID: 11ea2e6efa95
Revises: 
Create Date: 2025-08-11 12:38:17.841054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ea2e6efa95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_booking_form')
    with op.batch_alter_table('booking_form', schema=None) as batch_op:
        batch_op.create_unique_constraint('_booking_confirmation_company_uc', ['confirmation_code', 'company_id'])

    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('states',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.alter_column('states',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('booking_form', schema=None) as batch_op:
        batch_op.drop_constraint('_booking_confirmation_company_uc', type_='unique')

    op.create_table('_alembic_tmp_booking_form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guest_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('check_in_date', sa.DATE(), nullable=False),
    sa.Column('check_out_date', sa.DATE(), nullable=False),
    sa.Column('property_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('unit_id', sa.INTEGER(), nullable=False),
    sa.Column('number_of_nights', sa.INTEGER(), nullable=False),
    sa.Column('number_of_guests', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('booking_source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('confirmation_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('adults', sa.INTEGER(), nullable=True),
    sa.Column('children', sa.INTEGER(), nullable=True),
    sa.Column('infants', sa.INTEGER(), nullable=True),
    sa.Column('booking_date', sa.DATE(), nullable=True),
    sa.Column('is_cancelled', sa.BOOLEAN(), nullable=True),
    sa.Column('import_source', sa.VARCHAR(length=200), nullable=True),
    sa.Column('import_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_code', 'company_id', name='_booking_confirmation_company_uc')
    )
    # ### end Alembic commands ###
